### ISSUE TITLE
Project lacks a license

### ISSUE THREAD

**Issue by penpendede** [Xtrendence/X-Notify#2]
I want to use X-Notify in a project that is intended to have a theme definition and uses less for styling. I already created a fork but noticed that your project has no explicit license. I am confident that this was just an oversight as you usually do not publish projects on github  that are not meant to be Open Source. On the other hand, if this is intentionally so I will of course  remove the fork. This is what github writes on the topic (see https://docs.github.com/en/github/creating-cloning-and-archiving-repositories/creating-a-repository-on-github/licensing-a-repository): 

<blockquote>
You're under no obligation to choose a license. However, without a license, the default copyright laws apply, meaning that you retain all rights to your source code and no one may reproduce, distribute, or create derivative works from your work. If you're creating an open source project, we strongly encourage you to include an open source license. The Open Source Guide provides additional guidance on choosing the correct license for your project.
</blockquote>

My personal favorite is the ISC license (https://opensource.org/licenses/ISC) due to its simplicity. It also is the default license used by npm.

**Comment by Xtrendence** [comment]
Sorry about that, it was indeed an oversight. I've added an MIT license, so you can go ahead and use or modify any part of the project you want and include it in a commercial application or wherever else you want it. Thank you for bringing this to my attention.
